language: minimal

sudo: false

env:
  - MOZ_HEADLESS=1

addons:
  firefox: latest

matrix:
  fast_finish: true
  include:
  - name: default-python2
    env: TEST_TARGET=default PY=2.7
  - name: default
    env: TEST_TARGET=default PY=3.7
  - name: coding_standards
    env: TEST_TARGET=coding_standards PY=3.7


before_install:
  - wget http://bit.ly/miniconda -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no --set show_channel_urls true
  - conda update conda
  - conda config --remove channels defaults --force
  - conda config --add channels conda-forge --force
  - conda create --name TEST python=$PY --file requirements.txt --file requirements-dev.txt
  - source activate TEST
  # firefox headless driver
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-linux64.tar.gz -O geckodriver.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver

install:
    - python setup.py sdist && version=$(python setup.py --version) && pushd dist  && pip install branca-${version}.tar.gz && popd

script:
  - if [[ $TEST_TARGET == 'default' ]]; then
      cp -r tests/ /tmp && cd /tmp ;
      py.test -vv tests ;
    fi

  - if [[ $TEST_TARGET == 'coding_standards' ]]; then
      flake8 --max-line-length=105 branca --exclude=_version.py ;
      flake8 --max-line-length=105 tests ;
    fi

  deploy:
  skip_cleanup: true
  provider: pypi
  user: ocefpaf
  password:
    secure: "M5aQahIqYdA8XwfM2SwwWmsRWn7Vybm3iekv4BbIpi36gVZmJa/ZxTdzP4/eg7F8MgUMKY1hNEBKP0XkFuDC6tW9W95wP7vPAKeevm1Uvjil/fjbsFjG7AAgXgUru5sGZsleTCvjaCiL2vS2FlMyG8dGN5kj+kO9QxWaOmwvPV02oCDNacKpxyvBiZgT7CtIHhKyaNHGl1epbBdAgEm/VibhW93VkgSw8+FilZ1+8RElpg8DV4cl/Cv+vcCjpmKIS2spZDalr+h/MKCwZtw6cJ9pwGu+SUl1HKGz9YA01u2Yqov1INlGzohp1Tw/R00zaE0vo/8b8CIdQBAZjcc6ZxyCcLUcAu3bHowvWHuRZ6qG8JFHT3ISv4vDSMdNPeeDEX1ChetZtwA1RP5pCw6QoKTI0JgEyiFRwgVif2YZOvGcopmzQhfhYxpLsKgAss8sA2gBPKzZWKUmQPh1rbqjVaBAoMimbBPFMJdC6c6Ks23srSbsY438q/GAKiUyMWoxnfWwie/fhz8h5UjAwZ4glJdh5pQ51ZE3Vwk1xMsxj1aTnGGF6GmsXsrCnC4zz20tX12QI35ApcdD3ot8RkpgxxWU4N6Fh8R8zEsS5RReeDKbWz6n5c283d+FJczYztdEbNklM5mGry7kzWJzYIGMrjnSLZdOWoAs2zYMWE/RbTs="
  distributions: sdist bdist_wheel
  upload_docs: no
  on:
    repo: python-visualization/branca
    tags: true
    all_branches: master
    condition: '$TEST_TARGET == "default"'
